@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "user-3",
    "fullName": "Usuário 3",
    "email": "user3@email.com",
    "password": "123456789@",
    "cpf": "21234567800",
    "position": "user",
    "photoUrl": "https://cdn.icon-icons.com/icons2/788/PNG/512/user-1_icon-icons.com_65106.png"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "password": "123456789@",
    "cpf": "01234567800"
}

###

# @name fetch-users
GET {{baseUrl}}/accounts
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name fetch-user
GET {{baseUrl}}/accounts/226adfed-848d-408c-96e7-38011322ca93
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name edit-user
PUT {{baseUrl}}/accounts/e0446412-ec9c-452a-bac7-095d85012fc7
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "admin 3",
    "fullName": "admin",
    "email": "admin4@email.com",
    "position": "admin"
}

###

# @name delete-user
DELETE {{baseUrl}}/accounts/6f05c407-933c-4edf-9a91-502038487f6a
Content-Type: application/json
Authorization: Bearer {{authToken}}


###
# @name fetch_recent_products
GET {{baseUrl}}/products?page=1&orderByDate=desc&orderByAlphabetic=asc
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create-product
POST {{baseUrl}}/products
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Produto Teste 23",
    "price": 1200,
    "quantity": 12,
    "createdAt": "2024-10-04T15:30:00Z"
}

###
# @name fetch_product
GET {{baseUrl}}/products/c25e2c45-fb67-45d8-980b-42da7b57f443
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name edit-product
PUT {{baseUrl}}/products/202b55b5-2cb4-4f45-98c1-5fe4ac208406
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Produto Editado",
    "price": 1500,
    "quantity": 2,
    "createdAt": "2024-10-06T15:30:00Z"
}

###

# @name delete-product
DELETE {{baseUrl}}/products/202b55b5-2cb4-4f45-98c1-5fe4ac208406
Content-Type: application/json
Authorization: Bearer {{authToken}}