@baseUrl = http://localhost:4000
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "admin",
    "fullName": "admin",
    "email": "admin4@email.com",
    "password": "123456789@",
    "cpf": "01234567800",
    "position": "admin",
    "photoUrl": "https://avatars.githubusercontent.com/u/96916125?v=4"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "password": "123456789@",
    "cpf": "01234567800"
}

###

# @name fetch-user
GET {{baseUrl}}/accounts/e0446412-ec9c-452a-bac7-095d85012fc7
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name edit-user
PUT {{baseUrl}}/accounts/e0446412-ec9c-452a-bac7-095d85012fc7
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "admin 3",
    "fullName": "admin",
    "email": "admin4@email.com",
    "position": "admin"
}


###
# @name fetch_recent_products
GET {{baseUrl}}/products?page=1&orderByDate=desc&orderByAlphabetic=asc
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create-product
POST {{baseUrl}}/products
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Produto Teste 23",
    "price": 1200,
    "quantity": 12,
    "createdAt": "2024-10-04T15:30:00Z"
}

###
# @name fetch_product
GET {{baseUrl}}/products/c25e2c45-fb67-45d8-980b-42da7b57f443
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name edit-product
PUT {{baseUrl}}/products/202b55b5-2cb4-4f45-98c1-5fe4ac208406
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Produto Editado",
    "price": 1500,
    "quantity": 2,
    "createdAt": "2024-10-06T15:30:00Z"
}

###

# @name delete-product
DELETE {{baseUrl}}/products/202b55b5-2cb4-4f45-98c1-5fe4ac208406
Content-Type: application/json
Authorization: Bearer {{authToken}}