version: '3.8'

services:
  mysql:
    container_name: txai-server
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'docker'
      MYSQL_DATABASE: 'txai-database'
    volumes:
      - ./data/sql:/var/lib/mysql
